# يفعّل مجموعة لنتات Flutter الموصى بها
include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true         # يفرض التحويلات الصريحة
    strict-inference: true     # يفرض استدلال أنماط أدق
    strict-raw-types: true     # يمنع الأنماط الخام بدون معاملات نوع
  exclude:
    - build/**
    - ios/**/Generated*.xcconfig
    - ios/Runner/GeneratedPluginRegistrant.*
    - android/**/GeneratedPluginRegistrant*.*
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
  errors:
    # ارفع بعض اللنتات الحرجة إلى Error
    use_build_context_synchronously: error
    invalid_use_of_protected_member: error
    avoid_print: warning
    always_use_package_imports: warning

linter:
  rules:
    # موجودة لديك وممتازة
    avoid_print: true
    prefer_single_quotes: true
    always_use_package_imports: true
    unnecessary_late: true
    prefer_final_locals: true
    directives_ordering: true
    cancel_subscriptions: true
    close_sinks: true

    # إضافات موصى بها (أمان/جودة)
    avoid_dynamic_calls: true
    avoid_returning_null_for_void: true
    prefer_final_fields: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    unawaited_futures: true
    use_key_in_widget_constructors: true
    require_trailing_commas: true
    no_runtimeType_toString: true
    sort_constructors_first: true
    sized_box_for_whitespace: true
    use_colored_box: true
