name: Flutter CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze --no-fatal-infos

      - name: Format check
        run: |
          dart format --set-exit-if-changed .

      - name: Run tests
        run: flutter test -r expanded
